apiVersion: v1
kind: Service
metadata:
  name: prometheus-app-qa
spec:
  selector:
    app: prometheus-app-qa
    tier: monitoring
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: prometheus-app-qa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-app-qa
        tier: monitoring
    spec:
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: prometheus-app-web-qa
        image: prom/prometheus
        ports:
        - containerPort: 9090
          name: prom
          protocol: TCP
        volumeMounts:
        - name: prom_data
          mountPath: /prometheus
      volumes:
      - name: prom_data
        azureDisk:
          kind: Managed
          diskName: dsk_prom1
          diskURI: ...


